/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import controller.MenuController;
import controller.MenuController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author vicbaptista
 */
public class MenuView extends javax.swing.JFrame {

    //Atributo para conectar a tela com sua classe de controle
    private MenuController controller = new MenuController(MenuView.this);
    
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setExtendedState(MAXIMIZED_BOTH);
        controller.date();
        controller.liveTime();
        controller.carregarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProduto = new javax.swing.JPanel();
        btProdutos = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanelFornecedor = new javax.swing.JPanel();
        btFornecedor = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanelFuncionario = new javax.swing.JPanel();
        btFuncionarios = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanelVenda = new javax.swing.JPanel();
        btVendas = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanelCompra = new javax.swing.JPanel();
        btCompras = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanelCliente = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanelSair = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelLateralDireito = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVenda = new javax.swing.JMenuItem();
        jMenuCompas = new javax.swing.JMenu();
        jMenuItemCompra = new javax.swing.JMenuItem();
        jMenuContas = new javax.swing.JMenu();
        jMenuItemContaReceber = new javax.swing.JMenuItem();
        jMenuItemContaPagar = new javax.swing.JMenuItem();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Comercial de Vendas");
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelProduto.setPreferredSize(new java.awt.Dimension(0, 80));

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setContentAreaFilled(false);
        btProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProdutos.setFocusPainted(false);
        btProdutos.setMaximumSize(new java.awt.Dimension(127, 39));
        btProdutos.setMinimumSize(new java.awt.Dimension(127, 39));
        btProdutos.setPreferredSize(new java.awt.Dimension(127, 39));
        btProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProdutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProdutosMouseExited(evt);
            }
        });
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(200, 110, 60));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelProdutoLayout = new javax.swing.GroupLayout(jPanelProduto);
        jPanelProduto.setLayout(jPanelProdutoLayout);
        jPanelProdutoLayout.setHorizontalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(btProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(250, 250, 250))
        );
        jPanelProdutoLayout.setVerticalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanelFornecedor.setPreferredSize(new java.awt.Dimension(0, 80));

        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fornecedor.png"))); // NOI18N
        btFornecedor.setText("Fornecedores");
        btFornecedor.setContentAreaFilled(false);
        btFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFornecedor.setFocusPainted(false);
        btFornecedor.setMaximumSize(new java.awt.Dimension(127, 39));
        btFornecedor.setMinimumSize(new java.awt.Dimension(127, 39));
        btFornecedor.setPreferredSize(new java.awt.Dimension(127, 39));
        btFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFornecedorMouseExited(evt);
            }
        });
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(105, 200, 100));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFornecedorLayout = new javax.swing.GroupLayout(jPanelFornecedor);
        jPanelFornecedor.setLayout(jPanelFornecedorLayout);
        jPanelFornecedorLayout.setHorizontalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedorLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(btFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242))
        );
        jPanelFornecedorLayout.setVerticalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        btFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionario.png"))); // NOI18N
        btFuncionarios.setText("Funcionários");
        btFuncionarios.setContentAreaFilled(false);
        btFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFuncionarios.setFocusPainted(false);
        btFuncionarios.setMaximumSize(new java.awt.Dimension(127, 39));
        btFuncionarios.setMinimumSize(new java.awt.Dimension(127, 39));
        btFuncionarios.setPreferredSize(new java.awt.Dimension(127, 39));
        btFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFuncionariosMouseExited(evt);
            }
        });
        btFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionariosActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(160, 105, 230));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFuncionarioLayout = new javax.swing.GroupLayout(jPanelFuncionario);
        jPanelFuncionario.setLayout(jPanelFuncionarioLayout);
        jPanelFuncionarioLayout.setHorizontalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addComponent(btFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(256, 256, 256))
        );
        jPanelFuncionarioLayout.setVerticalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanelVenda.setPreferredSize(new java.awt.Dimension(0, 80));

        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venda.gif"))); // NOI18N
        btVendas.setText("Vendas");
        btVendas.setContentAreaFilled(false);
        btVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVendas.setFocusPainted(false);
        btVendas.setMaximumSize(new java.awt.Dimension(127, 39));
        btVendas.setMinimumSize(new java.awt.Dimension(127, 39));
        btVendas.setPreferredSize(new java.awt.Dimension(127, 39));
        btVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVendasMouseExited(evt);
            }
        });
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(3, 190, 72));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(btVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(255, 255, 255))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanelCompra.setPreferredSize(new java.awt.Dimension(0, 80));

        btCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras (1).png"))); // NOI18N
        btCompras.setText("Compras");
        btCompras.setContentAreaFilled(false);
        btCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCompras.setFocusPainted(false);
        btCompras.setMaximumSize(new java.awt.Dimension(127, 39));
        btCompras.setMinimumSize(new java.awt.Dimension(127, 39));
        btCompras.setPreferredSize(new java.awt.Dimension(127, 39));
        btCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btComprasMouseExited(evt);
            }
        });
        btCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprasActionPerformed(evt);
            }
        });

        jPanel20.setBackground(new java.awt.Color(230, 190, 25));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCompraLayout = new javax.swing.GroupLayout(jPanelCompra);
        jPanelCompra.setLayout(jPanelCompraLayout);
        jPanelCompraLayout.setHorizontalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCompraLayout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(btCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(257, 257, 257))
        );
        jPanelCompraLayout.setVerticalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCompraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanelCliente.setPreferredSize(new java.awt.Dimension(0, 80));

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setContentAreaFilled(false);
        btClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btClientes.setFocusPainted(false);
        btClientes.setMaximumSize(new java.awt.Dimension(127, 39));
        btClientes.setMinimumSize(new java.awt.Dimension(127, 39));
        btClientes.setPreferredSize(new java.awt.Dimension(127, 39));
        btClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btClientesMouseExited(evt);
            }
        });
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(55, 135, 230));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(btClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(257, 257, 257))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanelSair.setPreferredSize(new java.awt.Dimension(0, 80));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setContentAreaFilled(false);
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.setFocusPainted(false);
        btSair.setMaximumSize(new java.awt.Dimension(127, 39));
        btSair.setMinimumSize(new java.awt.Dimension(127, 39));
        btSair.setPreferredSize(new java.awt.Dimension(127, 39));
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSairMouseExited(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário:");

        jLabelUsuario.setText("nomeUsuario");

        jPanel23.setBackground(new java.awt.Color(170, 25, 25));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanelSairLayout = new javax.swing.GroupLayout(jPanelSair);
        jPanelSair.setLayout(jPanelSairLayout);
        jPanelSairLayout.setHorizontalGroup(
            jPanelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSairLayout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuario)
                .addGap(120, 120, 120)
                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSairLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSairLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanelSairLayout.setVerticalGroup(
            jPanelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSairLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelLateralDireitoLayout = new javax.swing.GroupLayout(jPanelLateralDireito);
        jPanelLateralDireito.setLayout(jPanelLateralDireitoLayout);
        jPanelLateralDireitoLayout.setHorizontalGroup(
            jPanelLateralDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanelLateralDireitoLayout.setVerticalGroup(
            jPanelLateralDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemFornecedor.setText("Fornecedores");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFornecedor);

        jMenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemProduto);

        jMenuItemFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemFuncionario.setText("Funcionários");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFuncionario);

        jMenuBar1.add(jMenuCadastro);

        jMenuEstoque.setText("Estoque");

        jMenu7.setText("Controle de Estoque");

        jMenuItemEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemEstoque.setText("Entrada de Estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemEstoque);

        jMenuEstoque.add(jMenu7);

        jMenu8.setText("Relatórios");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem6.setText("Produtos em Falta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuEstoque.add(jMenu8);

        jMenuBar1.add(jMenuEstoque);

        jMenuVendas.setText("Vendas");

        jMenuItemVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItemVenda.setText("Efetuar Venda");
        jMenuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendaActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemVenda);

        jMenuBar1.add(jMenuVendas);

        jMenuCompas.setText("Compras");

        jMenuItemCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItemCompra.setText("Efetuar Compra");
        jMenuItemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompraActionPerformed(evt);
            }
        });
        jMenuCompas.add(jMenuItemCompra);

        jMenuBar1.add(jMenuCompas);

        jMenuContas.setText("Contas");

        jMenuItemContaReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItemContaReceber.setText("Contas a Receber");
        jMenuItemContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContaReceberActionPerformed(evt);
            }
        });
        jMenuContas.add(jMenuItemContaReceber);

        jMenuItemContaPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItemContaPagar.setText("Contas a Pagar");
        jMenuItemContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContaPagarActionPerformed(evt);
            }
        });
        jMenuContas.add(jMenuItemContaPagar);

        jMenuBar1.add(jMenuContas);

        jMenuSistema.setText("Sistema");
        jMenuSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSistemaActionPerformed(evt);
            }
        });

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemSobre);
        jMenuSistema.add(jSeparator1);

        jMenuItemLogout.setText("Logout Escape");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemLogout);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemSair);

        jMenuBar1.add(jMenuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jPanelFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jPanelFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jPanelVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jPanelCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(jPanelSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanelLateralDireito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelSair, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jPanelLateralDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        try {
            controller.botaoSair();
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        controller.iniciaCliente();
    }//GEN-LAST:event_btClientesActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        controller.iniciaFornecedor();
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClientesMouseEntered
        controller.mudaCorBotaoCliente();
    }//GEN-LAST:event_btClientesMouseEntered

    private void btClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClientesMouseExited
        controller.resetaCorBotaoCliente();
    }//GEN-LAST:event_btClientesMouseExited

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        controller.iniciaProduto();
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprasActionPerformed
        controller.iniciaCompra();
    }//GEN-LAST:event_btComprasActionPerformed

    private void btFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFornecedorMouseEntered
        controller.mudaCorBotaoFornecedor();
    }//GEN-LAST:event_btFornecedorMouseEntered

    private void btFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFuncionariosMouseEntered
        controller.mudaCorBotaoFuncionario();
    }//GEN-LAST:event_btFuncionariosMouseEntered

    private void btProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutosMouseEntered
        controller.mudaCorBotaoProduto();
    }//GEN-LAST:event_btProdutosMouseEntered

    private void btVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendasMouseEntered
        controller.mudaCorBotaoVenda();
    }//GEN-LAST:event_btVendasMouseEntered

    private void btComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprasMouseEntered
        controller.mudaCorBotaoCompra();
    }//GEN-LAST:event_btComprasMouseEntered

    private void btSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseEntered
        controller.mudaCorBotaoSair();
    }//GEN-LAST:event_btSairMouseEntered

    private void btFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFornecedorMouseExited
        controller.resetaCorBotaoFornecedor();
    }//GEN-LAST:event_btFornecedorMouseExited

    private void btFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFuncionariosMouseExited
        controller.resetaCorBotaoFuncionario();
    }//GEN-LAST:event_btFuncionariosMouseExited

    private void btProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutosMouseExited
        controller.resetaCorBotaoProduto();
    }//GEN-LAST:event_btProdutosMouseExited

    private void btVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendasMouseExited
        controller.resetaCorBotaoVenda();
    }//GEN-LAST:event_btVendasMouseExited

    private void btComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprasMouseExited
        controller.resetaCorBotaoCompra();
    }//GEN-LAST:event_btComprasMouseExited

    private void btSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseExited
        controller.resetaCorBotaoSair();
    }//GEN-LAST:event_btSairMouseExited

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        controller.iniciaFornecedor();
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        controller.iniciaProduto();
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        controller.iniciaFuncionario();
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        controller.iniciaEstoque();
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendaActionPerformed
        controller.iniciaVenda();
    }//GEN-LAST:event_jMenuItemVendaActionPerformed

    private void jMenuItemContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContaReceberActionPerformed
        controller.iniciaContasReceber();
    }//GEN-LAST:event_jMenuItemContaReceberActionPerformed

    private void jMenuItemContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContaPagarActionPerformed
        controller.iniciaContasPagar();
    }//GEN-LAST:event_jMenuItemContaPagarActionPerformed

    private void btFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionariosActionPerformed
        controller.iniciaFuncionario();
    }//GEN-LAST:event_btFuncionariosActionPerformed

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        controller.iniciaVenda();
    }//GEN-LAST:event_btVendasActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        controller.iniciaCliente();
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompraActionPerformed
        controller.iniciaCompra();
    }//GEN-LAST:event_jMenuItemCompraActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        controller.iniciaSobre();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        try {
            controller.itemMenuLogout();
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSistemaActionPerformed
        
    }//GEN-LAST:event_jMenuSistemaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        try {
            controller.botaoSair();
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        controller.mudaIcone();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btCompras;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btFuncionarios;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCompas;
    private javax.swing.JMenu jMenuContas;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemCompra;
    private javax.swing.JMenuItem jMenuItemContaPagar;
    private javax.swing.JMenuItem jMenuItemContaReceber;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemVenda;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelCompra;
    private javax.swing.JPanel jPanelFornecedor;
    private javax.swing.JPanel jPanelFuncionario;
    private javax.swing.JPanel jPanelLateralDireito;
    private javax.swing.JPanel jPanelProduto;
    private javax.swing.JPanel jPanelSair;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtClientes() {
        return btClientes;
    }

    public void setBtClientes(JButton btClientes) {
        this.btClientes = btClientes;
    }

    public JButton getBtCompras() {
        return btCompras;
    }

    public void setBtCompras(JButton btCompras) {
        this.btCompras = btCompras;
    }

    public JButton getBtFornecedor() {
        return btFornecedor;
    }

    public void setBtFornecedor(JButton btFornecedor) {
        this.btFornecedor = btFornecedor;
    }

    public JButton getBtFuncionarios() {
        return btFuncionarios;
    }

    public void setBtFuncionarios(JButton btFuncionarios) {
        this.btFuncionarios = btFuncionarios;
    }

    public JButton getBtProdutos() {
        return btProdutos;
    }

    public void setBtProdutos(JButton btProdutos) {
        this.btProdutos = btProdutos;
    }

    public JButton getBtSair() {
        return btSair;
    }

    public void setBtSair(JButton btSair) {
        this.btSair = btSair;
    }

    public JButton getBtVendas() {
        return btVendas;
    }

    public void setBtVendas(JButton btVendas) {
        this.btVendas = btVendas;
    }

    public JMenuItem getjMenuItemCliente() {
        return jMenuItemCliente;
    }

    public void setjMenuItemCliente(JMenuItem jMenuItemCliente) {
        this.jMenuItemCliente = jMenuItemCliente;
    }

    public JMenuItem getjMenuItemCompra() {
        return jMenuItemCompra;
    }

    public void setjMenuItemCompra(JMenuItem jMenuItemCompra) {
        this.jMenuItemCompra = jMenuItemCompra;
    }

    public JMenuItem getjMenuItemContaPagar() {
        return jMenuItemContaPagar;
    }

    public void setjMenuItemContaPagar(JMenuItem jMenuItemContaPagar) {
        this.jMenuItemContaPagar = jMenuItemContaPagar;
    }

    public JMenuItem getjMenuItemContaReceber() {
        return jMenuItemContaReceber;
    }

    public void setjMenuItemContaReceber(JMenuItem jMenuItemContaReceber) {
        this.jMenuItemContaReceber = jMenuItemContaReceber;
    }

    public JMenuItem getjMenuItemEstoque() {
        return jMenuItemEstoque;
    }

    public void setjMenuItemEstoque(JMenuItem jMenuItemEstoque) {
        this.jMenuItemEstoque = jMenuItemEstoque;
    }

    public JMenuItem getjMenuItemFornecedor() {
        return jMenuItemFornecedor;
    }

    public void setjMenuItemFornecedor(JMenuItem jMenuItemFornecedor) {
        this.jMenuItemFornecedor = jMenuItemFornecedor;
    }

    public JMenuItem getjMenuItemFuncionario() {
        return jMenuItemFuncionario;
    }

    public void setjMenuItemFuncionario(JMenuItem jMenuItemFuncionario) {
        this.jMenuItemFuncionario = jMenuItemFuncionario;
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    public void setjMenuItemLogout(JMenuItem jMenuItemLogout) {
        this.jMenuItemLogout = jMenuItemLogout;
    }

    public JMenuItem getjMenuItemProduto() {
        return jMenuItemProduto;
    }

    public void setjMenuItemProduto(JMenuItem jMenuItemProduto) {
        this.jMenuItemProduto = jMenuItemProduto;
    }

    public JMenuItem getjMenuItemSair() {
        return jMenuItemSair;
    }

    public void setjMenuItemSair(JMenuItem jMenuItemSair) {
        this.jMenuItemSair = jMenuItemSair;
    }

    public JMenuItem getjMenuItemSobre() {
        return jMenuItemSobre;
    }

    public void setjMenuItemSobre(JMenuItem jMenuItemSobre) {
        this.jMenuItemSobre = jMenuItemSobre;
    }

    public JMenuItem getjMenuItemVenda() {
        return jMenuItemVenda;
    }

    public void setjMenuItemVenda(JMenuItem jMenuItemVenda) {
        this.jMenuItemVenda = jMenuItemVenda;
    }

    public JPanel getjPanelCliente() {
        return jPanelCliente;
    }

    public void setjPanelCliente(JPanel jPanelCliente) {
        this.jPanelCliente = jPanelCliente;
    }

    public JPanel getjPanelCompra() {
        return jPanelCompra;
    }

    public void setjPanelCompra(JPanel jPanelCompra) {
        this.jPanelCompra = jPanelCompra;
    }

    public JPanel getjPanelFornecedor() {
        return jPanelFornecedor;
    }

    public void setjPanelFornecedor(JPanel jPanelFornecedor) {
        this.jPanelFornecedor = jPanelFornecedor;
    }

    public JPanel getjPanelFuncionario() {
        return jPanelFuncionario;
    }

    public void setjPanelFuncionario(JPanel jPanelFuncionario) {
        this.jPanelFuncionario = jPanelFuncionario;
    }

    public JPanel getjPanelProduto() {
        return jPanelProduto;
    }

    public void setjPanelProduto(JPanel jPanelProduto) {
        this.jPanelProduto = jPanelProduto;
    }

    public JPanel getjPanelSair() {
        return jPanelSair;
    }

    public void setjPanelSair(JPanel jPanelSair) {
        this.jPanelSair = jPanelSair;
    }

    public JPanel getjPanelVenda() {
        return jPanelVenda;
    }

    public void setjPanelVenda(JPanel jPanelVenda) {
        this.jPanelVenda = jPanelVenda;
    }

    public JPanel getjPanelLateralDireito() {
        return jPanelLateralDireito;
    }

    public void setjPanelLateralDireito(JPanel jPanelLateralDireito) {
        this.jPanelLateralDireito = jPanelLateralDireito;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabelUsuario() {
        return jLabelUsuario;
    }

    public void setjLabelUsuario(JLabel jLabelUsuario) {
        this.jLabelUsuario = jLabelUsuario;
    }

    public JMenu getjMenuCadastro() {
        return jMenuCadastro;
    }

    public void setjMenuCadastro(JMenu jMenuCadastro) {
        this.jMenuCadastro = jMenuCadastro;
    }

    public JMenu getjMenuCompas() {
        return jMenuCompas;
    }

    public void setjMenuCompas(JMenu jMenuCompas) {
        this.jMenuCompas = jMenuCompas;
    }

    public JMenu getjMenuContas() {
        return jMenuContas;
    }

    public void setjMenuContas(JMenu jMenuContas) {
        this.jMenuContas = jMenuContas;
    }

    public JMenu getjMenuEstoque() {
        return jMenuEstoque;
    }

    public void setjMenuEstoque(JMenu jMenuEstoque) {
        this.jMenuEstoque = jMenuEstoque;
    }

    public JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    public void setjMenuItem6(JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    public JMenu getjMenuSistema() {
        return jMenuSistema;
    }

    public void setjMenuSistema(JMenu jMenuSistema) {
        this.jMenuSistema = jMenuSistema;
    }

    public JMenu getjMenuVendas() {
        return jMenuVendas;
    }

    public void setjMenuVendas(JMenu jMenuVendas) {
        this.jMenuVendas = jMenuVendas;
    }
    
}
